### ISSUE TITLE
Reverse stationarization

### ISSUE THREAD

**Issue by ghost** [shaypal5/stationarizer#2]
Is it possible to use the library to detransform the series?

**Comment by shaypal5** [comment]
Hmmmm.

I think by definition - no.

Think about it from a generative point of view:
Let's start with some specific stationary process, S.
Now, let's add to it some trend T1. We get a process P1=T1+S.
Let's do the same with T2 and T3.
We have three stationary+trend processes now: P1, P2, and P3.

Now let's pull from each a realization of it for t steps:
We get three time series.

Now let's assume the process described in the methodology section determines for all three that the presence of a trend cannot be reject, so all three are de-trended.
You should get roughly equivalent (note: not identical) realizations of the same stationary process.

How could you tell which was the trend of which? That's the whole point of de-trending:
To remove the trend information in the series. Ideally, it should be retained in the samples at all.

Practically, I have no idea if the information is really removed completely, or if some method can recover it, but it's definitely not an equivalent process to what is done here.

Cheers,  :)
Shay
